version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: genesisrk
    main: .
    binary: genesisrk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/aeltai/hangar-genesis/internal/genesis.Version={{.Version}}
      - -X github.com/aeltai/hangar-genesis/internal/genesis.HangarVersion=v1.9.4

archives:
  - id: genesisrk
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - config.example.yaml
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
